name: sync-fork
env: 
  UPSTREAM_URL: "http://github.com:input-output-hk/cardano-node.git"
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{env.UPSTREAM_URL}}
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.WORKFLOW_TOKEN }}
